import './globals.css'

export const metadata = {
  title: '第七宇宙',
  description: 'Generated by 第七宇宙',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
